### ISSUE TITLE
求助一下

### ISSUE THREAD

**Issue by que01** [OCD0711/MSI-B360M-EFI#1]
昨天用一键HiDPI那个脚本把系统高挂了。。。晚上回去试试你这个，因为看情况是最完善一个。

我准备用苹果小兵那个带Clover的镜像。请问这个EFI是直接安装之前就放进U盘EFI去 还是用自带的EFI安装好再替换到硬盘EFI去呢？

**Comment by zhanglinbo** [comment]
做好备份，都可以

**Comment by LifeToyer** [comment]
用黑果小兵带efi的镜像，还没到安装界面就黑屏，看你的支持HDMI输出，把efi分区替换成你的，结果安装过程卡在苹果标读条界面，怎么办？

**Comment by ocd0711** [comment]
> 用黑果小兵带efi的镜像，还没到安装界面就黑屏，看你的支持HDMI输出，把efi分区替换成你的，结果安装过程卡在苹果标读条界面，怎么办？

这个你确定你是B360M不是z370?

**Comment by ocd0711** [comment]
可以直接用于安装

**Comment by LifeToyer** [comment]
> > 用黑果小兵带efi的镜像，还没到安装界面就黑屏，看你的支持HDMI输出，把efi分区替换成你的，结果安装过程卡在苹果标读条界面，怎么办？
> 
> 这个你确定你是B360M不是z370?

确定是B360M迫击炮，刚刚又试了了你最新的EFI，哆嗦模式下是卡在gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0。我这边BIOS应该没问题，cfg vtd什么都关了，v12和v15 BIOS都试了，都是卡这个地方

**Comment by ocd0711** [comment]
> > > 用黑果小兵带efi的镜像，还没到安装界面就黑屏，看你的支持HDMI输出，把efi分区替换成你的，结果安装过程卡在苹果标读条界面，怎么办？
> > 
> > 
> > 这个你确定你是B360M不是z370?
> 
> 确定是B360M迫击炮，刚刚又试了了你最新的EFI，哆嗦模式下是卡在gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0。我这边BIOS应该没问题，cfg vtd什么都关了，v12和v15 BIOS都试了，都是卡这个地方

这个问题不是efi问题是你bios设置问题...解决办法恢复bios默认设置还没用的话抠电池给bios放电强行重制就行了

**Comment by LifeToyer** [comment]
> > > > 用黑果小兵带efi的镜像，还没到安装界面就黑屏，看你的支持HDMI输出，把efi分区替换成你的，结果安装过程卡在苹果标读条界面，怎么办？
> > > 
> > > 
> > > 这个你确定你是B360M不是z370?
> > 
> > 
> > 确定是B360M迫击炮，刚刚又试了了你最新的EFI，哆嗦模式下是卡在gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0。我这边BIOS应该没问题，cfg vtd什么都关了，v12和v15 BIOS都试了，都是卡这个地方
> 
> 这个问题不是efi问题是你bios设置问题...解决办法恢复bios默认设置还没用的话抠电池给bios放电强行重制就行了

给BIOS卸电池，5分钟再装上，还是一样卡gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0，已经好几天我快崩溃了，这到底是什么毛病啊，一模一样的主板一模一样的BIOS和efi

**Comment by LifeToyer** [comment]
> 昨天用一键HiDPI那个脚本把系统高挂了。。。晚上回去试试你这个，因为看情况是最完善一个。
> 
> 我准备用苹果小兵那个带Clover的镜像。请问这个EFI是直接安装之前就放进U盘EFI去 还是用自带的EFI安装好再替换到硬盘EFI去呢？

你安装前替换这个EFI，能进安装界面吗？

**Comment by ocd0711** [comment]
> gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0

放电是拔掉电源扣掉电池,然后按几次电源键...efi直接用来安装或者启动都没问题,如果安装界面能进但是你现在系统无法进入的话你得考虑重装了

**Comment by LifeToyer** [comment]
> > gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0
> 
> 放电是拔掉电源扣掉电池,然后按几次电源键...efi直接用来安装或者启动都没问题,如果安装界面能进但是你现在系统无法进入的话你得考虑重装了

我是装都没装，无法进入安装界面，卡那个地方进不去安装界面。我再试试你说的

**Comment by ocd0711** [comment]
> > > gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0
> > 
> > 
> > 放电是拔掉电源扣掉电池,然后按几次电源键...efi直接用来安装或者启动都没问题,如果安装界面能进但是你现在系统无法进入的话你得考虑重装了
> 
> 我是装都没装，无法进入安装界面，卡那个地方进不去安装界面。我再试试你说的

这个问题你单独提一个issue吧...如果没用的话我周一回公司改个给你看下

**Comment by que01** [comment]
> > > > > 用黑果小兵带efi的镜像，还没到安装界面就黑屏，看你的支持HDMI输出，把efi分区替换成你的，结果安装过程卡在苹果标读条界面，怎么办？
> > > > 
> > > > 
> > > > 这个你确定你是B360M不是z370?
> > > 
> > > 
> > > 确定是B360M迫击炮，刚刚又试了了你最新的EFI，哆嗦模式下是卡在gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0。我这边BIOS应该没问题，cfg vtd什么都关了，v12和v15 BIOS都试了，都是卡这个地方
> > 
> > 
> > 这个问题不是efi问题是你bios设置问题...解决办法恢复bios默认设置还没用的话抠电池给bios放电强行重制就行了
> 
> 给BIOS卸电池，5分钟再装上，还是一样卡gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0，已经好几天我快崩溃了，这到底是什么毛病啊，一模一样的主板一模一样的BIOS和efi

这个问题呢，我说下我是怎么安装的。
1.首先是第一步bios 如果你版本不是v12 那么就用降级工具降级一下 在win10下操作。这个降级工具[点击下载](http://forum-sc.msi.com/index.php?topic=4531.0) 固件地址这个repo的readme里面有。
2.镜像 我这边用的苹果小兵最新的带clover的镜像。安装时候U盘里面的EFI需要改2个地方，
* U盘EFI里面的config.plist 你可以看到很多的config_xxx.plist 你需要吧uh630(这里除非你不是八代U是9代 不然就是630这个显卡)的重命名为config.plist 。原来的备份。
* 删除drivers64UEFI目录中AptioMemoryFix-64.efi，并从/EFI/CLOVER/drivers-off中找到OsxAptioFix2Drv-free2000.efi 把他复制到drivers64UEFI目录。
3. 确保有一个200M以上的EFI分区在你的硬盘中。
4. 断网安装就行了。完事后挂载硬盘的EFI分区 把这个repo里面的EFI放进去，主板改引导efi-clover那个就可以了。

我周五试过这个方案。一路下来15分钟就操作完毕了 毫无波折吧。

我这边主要配置 i5 8400 主板MSI b360m 迫击炮 显卡蓝宝石rx580 oc(2048版本据说可以刷vbios成570也可以黑 没试过) 硬盘hp ex920 512G
