### ISSUE TITLE
安装出错，panic

### ISSUE THREAD

**Issue by nnnnq** [OCD0711/MSI-B360M-EFI#13]
主板 MSI B360M mortar
CPU i5 9400F
显卡 RX580 白金版
SSD 三星970 evo plus
主板BIOS 7B23v15
-v模式准备安装的时候提示power supply una
vailable，然后进入安装，进度条到2minute的时候就重启，重启后我继续安装，就显示如下

![panic-2](https://user-images.githubusercontent.com/51987404/59744530-5aac2100-92a5-11e9-95e1-32c1b61b20ac.jpg)

**Comment by ocd0711** [comment]
panic去清空nvram和扣电池重置bios

**Comment by nnnnq** [comment]
> panic去清空nvram和扣电池重置bios

我用的是三星970 evo plus，看了有人说不支持，我回头试下


[https://www.tonymacx86.com/threads/do-the-samsung-970-evo-plus-drives-work-new-firmware-available-for-testing-5-20-19.270757/](url)

**Comment by ocd0711** [comment]
> > panic去清空nvram和扣电池重置bios
> 
> 我用的是三星970 evo plus，看了有人说不支持，我回头试下
> 
> [https://www.tonymacx86.com/threads/do-the-samsung-970-evo-plus-drives-work-new-firmware-available-for-testing-5-20-19.270757/](url)

三星970 evo plus把固态刷最新固件可以安...你可以自己刷下

**Comment by nnnnq** [comment]
我晚上刷了试下。



------------------ 原始邮件 ------------------
发件人: "OCD0711"<notifications@github.com>; 
发送时间: 2019年6月20日(星期四) 下午3:17
收件人: "OCD0711/MSI-B360M-EFI"<MSI-B360M-EFI@noreply.github.com>; 
抄送: "宁"<756355386@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [OCD0711/MSI-B360M-EFI] 安装出错，panic (#13)



  
panic去清空nvram和扣电池重置bios
  
我用的是三星970 evo plus，看了有人说不支持，我回头试下
 
https://www.tonymacx86.com/threads/do-the-samsung-970-evo-plus-drives-work-new-firmware-available-for-testing-5-20-19.270757/
  
三星970 evo plus把固态刷最新固件可以安...你可以自己刷下

**Comment by nnnnq** [comment]
> > > panic去清空nvram和扣电池重置bios
> > 
> > 
> > 我用的是三星970 evo plus，看了有人说不支持，我回头试下
> > [https://www.tonymacx86.com/threads/do-the-samsung-970-evo-plus-drives-work-new-firmware-available-for-testing-5-20-19.270757/](url)
> 
> 三星970 evo plus把固态刷最新固件可以安...你可以自己刷下

刷新三星硬盘固件能安装上了！
