### ISSUE TITLE
msi h370 carbon cpu 8500 新手求助

### ISSUE THREAD

**Issue by numberpig** [OCD0711/MSI-B360M-EFI#14]
问题描述：bios更新到最新的7b16v17，vt-d 等推荐的bios设置都一一设置完成后，用tonyx86的unibeast创建安装盘（mojove 10.14.5 ），结果卡在苹果进度条界面，无法进行。后续计划用命令行创建启动盘，手工安装最新版本clover 到usb上再试试 ，希望大侠能否指点一二：1.黑苹果过程中有哪些需要特别注意的（不修改或者处理就会无法安装的那种） 2.能否告知一下制作hackintosh都用到了哪些软件？ 非常感谢！！！

**Comment by milesking** [comment]
拿这个repo的efi替换unibeast生成的u盘里面的efi了嘛？如果没有的话用clover configurator 挂载u盘efi然后替换掉

**Comment by numberpig** [comment]
> 拿这个repo的efi替换unibeast生成的u盘里面的efi了嘛？如果没有的话用clover configurator 挂载u盘efi然后替换掉

 考虑主板的芯片组不一样，可以直接替换吗？我没有试，晚上回家试试你说的，非常感谢！

**Comment by ocd0711** [comment]
非B360M板子先用通用efi去安装,再尝试在我的上面修改

**Comment by numberpig** [comment]
> 非B360M板子先用通用efi去安装,再尝试在我的上面修改

恩，我对比了一下h370 和b360m ，主要usb 数量 音频芯片 有些区别 ，今天google了不少资料，对usb的驱动还有点模糊，我看您的代码里面SSDT-EC.aml和usb相关，也没有用USBInjectAll.kext,但是我看https://hackintosh.gitbook.io/-r-hackintosh-vanilla-desktop-guide/gathering-kexts 这篇文章里面又说要用，关于usb的驱动能否给一点意见和建议呢？万分感谢

**Comment by ocd0711** [comment]
> > 非B360M板子先用通用efi去安装,再尝试在我的上面修改
> 
> 恩，我对比了一下h370 和b360m ，主要usb 数量 音频芯片 有些区别 ，今天google了不少资料，对usb的驱动还有点模糊，我看您的代码里面SSDT-EC.aml和usb相关，也没有用USBInjectAll.kext,但是我看https://hackintosh.gitbook.io/-r-hackintosh-vanilla-desktop-guide/gathering-kexts 这篇文章里面又说要用，关于usb的驱动能否给一点意见和建议呢？万分感谢

SSDT-EC.aml和usbport.kext是我做的B360M usb定制驱动...你的话删掉之后将usbinjectall.kext放进去就行了,如果就你说的这些不同的话那是可以开机安装的,安装完成之后你只需要获取声卡id和定制usb驱动就行了

**Comment by numberpig** [comment]
> > > 非B360M板子先用通用efi去安装,再尝试在我的上面修改
> > 
> > 
> > 恩，我对比了一下h370 和b360m ，主要usb 数量 音频芯片 有些区别 ，今天google了不少资料，对usb的驱动还有点模糊，我看您的代码里面SSDT-EC.aml和usb相关，也没有用USBInjectAll.kext,但是我看https://hackintosh.gitbook.io/-r-hackintosh-vanilla-desktop-guide/gathering-kexts 这篇文章里面又说要用，关于usb的驱动能否给一点意见和建议呢？万分感谢
> 
> SSDT-EC.aml和usbport.kext是我做的B360M usb定制驱动...你的话删掉之后将usbinjectall.kext放进去就行了,如果就你说的这些不同的话那是可以开机安装的,安装完成之后你只需要获取声卡id和定制usb驱动就行了

恩，明白了，谢谢你的指点！我就是钻牛角尖非要买个h370，要不然直接用你们能省不少事情，不过这也是折腾的意义，再次感谢

**Comment by ocd0711** [comment]
> > > > 非B360M板子先用通用efi去安装,再尝试在我的上面修改
> > > 
> > > 
> > > 恩，我对比了一下h370 和b360m ，主要usb 数量 音频芯片 有些区别 ，今天google了不少资料，对usb的驱动还有点模糊，我看您的代码里面SSDT-EC.aml和usb相关，也没有用USBInjectAll.kext,但是我看https://hackintosh.gitbook.io/-r-hackintosh-vanilla-desktop-guide/gathering-kexts 这篇文章里面又说要用，关于usb的驱动能否给一点意见和建议呢？万分感谢
> > 
> > 
> > SSDT-EC.aml和usbport.kext是我做的B360M usb定制驱动...你的话删掉之后将usbinjectall.kext放进去就行了,如果就你说的这些不同的话那是可以开机安装的,安装完成之后你只需要获取声卡id和定制usb驱动就行了
> 
> 恩，明白了，谢谢你的指点！我就是钻牛角尖非要买个h370，要不然直接用你们能省不少事情，不过这也是折腾的意义，再次感谢

z370 比 b360m 板子上多一个usb2.0的口方便pcie网卡的蓝牙走usb....b360m的话需要分线或者放弃ubs2.0

**Comment by numberpig** [comment]
![image](https://user-images.githubusercontent.com/5226452/60003212-cecb3800-969c-11e9-87ad-b3f3d178ad7a.png)
02cs的网卡我还没买 ，不知道这个要占usb，不是pci-e的吗？我只是看帖子说安装的时候要用2.0 的usb口，也不清楚为什么

**Comment by ocd0711** [comment]
> ![image](https://user-images.githubusercontent.com/5226452/60003212-cecb3800-969c-11e9-87ad-b3f3d178ad7a.png)
> 02cs的网卡我还没买 ，不知道这个要占usb，不是pci-e的吗？我只是看帖子说安装的时候要用2.0 的usb口，也不清楚为什么

wifi是走pcie,蓝牙得走usb

**Comment by numberpig** [comment]
断断续续搞了十来天，总算是可以用了，有时间了我也把配置发上来，再次感谢最初的指导

**Comment by ocd0711** [comment]
> 断断续续搞了十来天，总算是可以用了，有时间了我也把配置发上来，再次感谢最初的指导

hh解决问题就行了..我也没帮什么忙..毕竟板子不再手上也不清楚
