### ISSUE TITLE
请教一下，关机主机不断电怎么解决？

### ISSUE THREAD

**Issue by Chave-Z** [OCD0711/MSI-B360M-EFI#15]
i5 9600k + 微星z390，虽然主板型号和你这边的不一样，但是微星的都应该差不多的吧，什么都正常，就是光机后主机不断电，重启也重启不成功，这个有解决办法么？

**Comment by ocd0711** [comment]
去处定制usb的usbport.kext和ssdt...替换成usbinjectall.kext

**Comment by ocd0711** [comment]
> 去处定制usb的usbport.kext和ssdt...替换成usbinjectall.kext

或者自己去定制你主板的

**Comment by Chave-Z** [comment]
有相关的教程链接么？不是我这个主板的也行，我刚入坑的小白，你怎么讲我并不懂怎么去搜索攻略，先谢了

**Comment by ocd0711** [comment]
删除acpi/patched下的ssdt-ec.aml,删除kexts/other下的USBPorts.kext,然后在kexts/other下放入USBInjectAll.kext

**Comment by ocd0711** [comment]
usb定制可以去看这个https://blog.daliansky.net/Intel-FB-Patcher-USB-Custom-Video.html

**Comment by Chave-Z** [comment]
好的呢，还有一个问题，我找到一个可以开关机的clover,那边的开关机是正常的，但是有其他的问题，我可以直接利用那边的USBInjectAll.kext么

**Comment by ocd0711** [comment]
> 好的呢，还有一个问题，我找到一个可以开关机的clover,那边的开关机是正常的，但是有其他的问题，我可以直接利用那边的USBInjectAll.kext么

USBInjectAll.kext 是非定制驱动,你直接用或者去下载最新版都可以...https://bitbucket.org/RehabMan/os-x-usb-inject-all/downloads/

**Comment by Chave-Z** [comment]
好的，我晚上试一下，谢谢了
