### ISSUE TITLE
i5 8400 b360m

### ISSUE THREAD

**Issue by gooff327** [OCD0711/MSI-B360M-EFI#17]
请问使用集显安装的时候能驱动hdmi吗 我的这块板子没有dp接口

**Comment by ocd0711** [comment]
可以..

**Comment by gooff327** [comment]
很遗憾 我的启动一般hdmi就没有信号了

**Comment by gooff327** [comment]
一半

**Comment by ocd0711** [comment]
> 很遗憾 我的启动一般hdmi就没有信号了

不是msi的板子?、

**Comment by gooff327** [comment]
嗯 是华擎的，没有dp接口 只有hdmi 尝试注入显示器也不行

**Comment by ocd0711** [comment]
> 嗯 是华擎的，没有dp接口 只有hdmi 尝试注入显示器也不行

hdmi是要修改hdmi接口配置的…非msi板子用这个efi不能保证有用除非碰巧一样
