### ISSUE TITLE
请问，同款主板，CPU9900K，无独显，不知道可否直接使用此efi？

### ISSUE THREAD

**Issue by zy13101437** [OCD0711/MSI-B360M-EFI#19]
之前使用黑果小兵的镜像装过一次，安装完进系统黑屏，不知道可否直接使用大神的efi？

**Comment by ocd0711** [comment]
可以

**Comment by ocd0711** [comment]
无独显是最合适的…安装的时候最好只接一个屏幕..如果出现黑屏拔插下显示器

**Comment by zy13101437** [comment]
我直接使用此efi，在引导之后直接就自动重启了，-v模式也没有卡住，啰嗦完还是重启，，，实在是不知道哪里有问题，搜不到，不知大神可否指教一二？

**Comment by zy13101437** [comment]
我装的是10.15b2，之前的问题都是-v卡住，有迹可循，这个直接重启实在是不知道如何处理了，，，

**Comment by zy13101437** [comment]
BIOS是7B23v15，

**Comment by ocd0711** [comment]
> 我装的是10.15b2，之前的问题都是-v卡住，有迹可循，这个直接重启实在是不知道如何处理了，，，

bios更新到16…然后拔电源扣电池重置bios…

**Comment by zy13101437** [comment]
感谢解答，我的BIOS更新到16还是直接重启，放弃了...非常感谢！
