### ISSUE TITLE
报个Bug 无法记忆上一次登录系统

### ISSUE THREAD

**Issue by que01** [OCD0711/MSI-B360M-EFI#2]
最新的EFI暂时还无法记忆上次登入的启动项里面去。

所以我google了一下 删了Emuvariableuefi-64.efi 。然后这块就正常了 不知道有没有其他副作用？

希望大佬修复一下这个小问题。。

**Comment by ocd0711** [comment]
Emuvariableuefi涉及nvram这块,你删掉会导致亮度无法保存和iMessage重复登陆的问题...我是单系统没有win..这个问题这两天看下到时候会更新

**Comment by ocd0711** [comment]
已找到其他办法修复已经更新
