### ISSUE TITLE
msi-b360m i3-8100主板usb2.0和usb3.0接口失效

### ISSUE THREAD

**Issue by hflyf123** [OCD0711/MSI-B360M-EFI#20]
感谢您提供的efi，我已经成功安装上了系统，但是主机只有机箱前面板上的usb3.0是正常工作的，主板上的usb2.0和3.0接口都不能正常工作，我该如何排查错误？

**Comment by ocd0711** [comment]
B360M MORTAR 和  B360M MORTAR TITANIUM 两块你应该是后者吧

**Comment by hflyf123** [comment]
> B360M MORTAR 和 B360M MORTAR TITANIUM 两块你应该是后者吧

我的就是迫击炮的普通版，在bios下，接口都是好的，且能识别（鼠标键盘可以正常使用），但是一进clover就不行了。
其他有用信息：
使用Hackintool然后用usb设备进行了检测，机箱背部的3个usb接口均无反应，前置有反应（变绿）

**Comment by hflyf123** [comment]
顺便在这问po主您一个问题，我觉得8100性能有点差，想换8700es 可以直接刷吗，需要修改什么吗。

**Comment by hflyf123** [comment]
我最终使用9600K + b360m mortar，目前遇到几个问题
1. 点击睡眠后过几秒会自动唤醒，或是没进入睡眠
2.主板后置面板上的usb接口失效

其他都比较完美。

**Comment by ocd0711** [comment]
> 我最终使用9600K + b360m mortar，目前遇到几个问题
> 
> 1. 点击睡眠后过几秒会自动唤醒，或是没进入睡眠
>    2.主板后置面板上的usb接口失效
> 
> 其他都比较完美。

用新的efi没问题

**Comment by hflyf123** [comment]
> > 我最终使用9600K + b360m mortar，目前遇到几个问题
> > 
> > 1. 点击睡眠后过几秒会自动唤醒，或是没进入睡眠
> >    2.主板后置面板上的usb接口失效
> > 
> > 其他都比较完美。
> 
> 用新的efi没问题

你好，我昨天下载了最新的efi文件，并在windows环境下将老的efi文件进行了替换，但是重启后我检查clover版本没有发生变化，我最初装系统的时候使用的是MSI-B360M-10.14.5-EFI-1.4这个版本，昨天用MSI-B360M-10.15-beta-EFI-2.0进行了替换，请问应该如何正确的替换？

**Comment by yjkddlt** [comment]
> 我最终使用9600K + b360m mortar，目前遇到几个问题
> 
> 1. 点击睡眠后过几秒会自动唤醒，或是没进入睡眠
>    2.主板后置面板上的usb接口失效
> 
> 其他都比较完美。

我的8700会不定时唤醒。

**Comment by ocd0711** [comment]
2.1修复了部分问题…usb口本身做了定制msi b360m是完美的…efi不要做任何更改,有问题重制下bios

**Comment by hflyf123** [comment]
> 2.1修复了部分问题…usb口本身做了定制msi b360m是完美的…efi不要做任何更改,有问题重制下bios

你好,我昨天用MSI-B360M-10.15-beta-EFI-2.0这个版本替换后重新格盘安装了一下,发现clover版本还是4945,但是我看更新日志写这个版本的efi clover已经升到5027了,使用的镜像是黑果小兵的10.14.6的,不知是哪里的问题?

**Comment by ocd0711** [comment]
> > 2.1修复了部分问题…usb口本身做了定制msi b360m是完美的…efi不要做任何更改,有问题重制下bios
> 
> 你好,我昨天用MSI-B360M-10.15-beta-EFI-2.0这个版本替换后重新格盘安装了一下,发现clover版本还是4945,但是我看更新日志写这个版本的efi clover已经升到5027了,使用的镜像是黑果小兵的10.14.6的,不知是哪里的问题?

仔细看tag..2.1才是5027...

**Comment by hflyf123** [comment]
> > > 2.1修复了部分问题…usb口本身做了定制msi b360m是完美的…efi不要做任何更改,有问题重制下bios
> > 
> > 
> > 你好,我昨天用MSI-B360M-10.15-beta-EFI-2.0这个版本替换后重新格盘安装了一下,发现clover版本还是4945,但是我看更新日志写这个版本的efi clover已经升到5027了,使用的镜像是黑果小兵的10.14.6的,不知是哪里的问题?
> 
> 仔细看tag..2.1才是5027...

好的,我晚上回去再更新一下试试,谢谢po主的更新,感谢!
