### ISSUE TITLE
HDMI电脑开机碎屏，全屏都是。

### ISSUE THREAD

**Issue by kalifun** [OCD0711/MSI-B360M-EFI#3]
配置B360M 迫击炮 + 8700
开机时加载一会logo后突然黑屏然后就是碎屏，就是麻麻点点的密集整个屏幕。重新拔插一下HDMI后，回到logo加载最后一点就可以登录了。能解答一下吗？感激不尽。

**Comment by ocd0711** [comment]
> 配置B360M 迫击炮 + 8700
> 开机时加载一会logo后突然黑屏然后就是碎屏，就是麻麻点点的密集整个屏幕。重新拔插一下HDMI后，回到logo加载最后一点就可以登录了。能解答一下吗？感激不尽。

已修复,周一会push上去..你周一来下载更新之后的就行了

**Comment by ocd0711** [comment]
已经修复..可以下载去测试

**Comment by kalifun** [comment]
特别感谢哦
