### ISSUE TITLE
dp接口显示花屏，无法识别显示器型号

### ISSUE THREAD

**Issue by Tuetle** [OCD0711/MSI-B360M-EFI#6]
使用dp接口的显示器会一闪一闪的花屏，偶尔黑屏几秒。显示器是acer vg270up ,2k分辨率

**Comment by ocd0711** [comment]
单显示区还是多个?hdmi/dvi口是否有占用.如果都没有的话bios放电/nvme清理下

**Comment by Tuetle** [comment]
> 单显示区还是多个?hdmi/dvi口是否有占用.如果都没有的话bios放电/nvme清理下

已经解决了，是显示器的兼容问题，谢谢

**Comment by ocd0711** [comment]
> > 单显示区还是多个?hdmi/dvi口是否有占用.如果都没有的话bios放电/nvme清理下
> 
> 已经解决了，是显示器的兼容问题，谢谢

ok,那我关闭 issuse 了
