### ISSUE TITLE
Reporting USB 3.0 Issues

### ISSUE THREAD

**Issue by WONGWAI1017** [OCD0711/MSI-B360M-EFI#8]
感謝，已經第一時間用上10.15了。所有方面都運作良好。但是有一個小問題就是使用您的efi啟動無法使用usb鼠標和鍵盤。刪除您的efi目錄下的所有ssdt和usb ports.kext可以使用。但是卻丟失了usb 3.0 5g速率.

**Comment by ocd0711** [comment]
已经修复...抱歉push之前忘了检查一下导致漏了点东西

**Comment by ocd0711** [comment]
测试没问题的话回复我,方便关闭issue

**Comment by WONGWAI1017** [comment]
感x您的回覆和修正！相PIssue已P]！感x

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
