### ISSUE TITLE
请您告知一下具体的电脑配置表

### ISSUE THREAD

**Issue by SwiftGraff** [OCD0711/MSI-B360M-EFI#9]
我在国外，购买电脑配件没有国内方便，能给一张配置的表吗？我试试照着买，CPU换成8代的i5可以吗？谢谢！

**Comment by ocd0711** [comment]
主板是B360M MORTAR就行了..u的话8代i5可以...内存和固态都没要求..网卡用BCM943602CS拆机卡转pcie

**Comment by SkyGrass** [comment]
> 主板是B360M MORTAR就行了..u的话8代i5可以...内存和固态都没要求..网卡用BCM943602CS拆机卡转pcie

主板上只有1个9针的usb插槽， 接了pcie 难道你放弃了前置USB ？

**Comment by ocd0711** [comment]
> > 主板是B360M MORTAR就行了..u的话8代i5可以...内存和固态都没要求..网卡用BCM943602CS拆机卡转pcie
> 
> 主板上只有1个9针的usb插槽， 接了pcie 难道你放弃了前置USB ？

前置usb2.0放弃了..3.0可以保留啊

**Comment by SkyGrass** [comment]
> > > 主板是B360M MORTAR就行了..u的话8代i5可以...内存和固态都没要求..网卡用BCM943602CS拆机卡转pcie
> > 
> > 
> > 主板上只有1个9针的usb插槽， 接了pcie 难道你放弃了前置USB ？
> 
> 前置usb2.0放弃了..3.0可以保留啊

可惜了啊

**Comment by milesking** [comment]
非要用2.0的话可以用3.0转2.0 9pin的线。不支持前置3.0的机箱真的可以换或者改造一下。这个班子有前置3.1接口，我都想在机箱上钻个孔diy3.1了

**Comment by SkyGrass** [comment]
> 非要用2.0的话可以用3.0转2.0 9pin的线。不支持前置3.0的机箱真的可以换或者改造一下。这个班子有前置3.1接口，我都想在机箱上钻个孔diy3.1了

我搞了个 9pin 1分2 的拓展器，分出来的接口，一个给前置usb2.0 、另一个给 peci 转接卡
